"""corrected feild

Revision ID: 24efbd4a01c5
Revises: d225f78a9b04
Create Date: 2026-03-17 19:38:29.005793

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '24efbd4a01c5'
down_revision: Union[str, Sequence[str], None] = 'd225f78a9b04'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workflows', sa.Column('user_id', sa.String(), nullable=False))
    op.drop_constraint(op.f('workflows_userId_fkey'), 'workflows', type_='foreignkey')
    op.create_foreign_key(None, 'workflows', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_column('workflows', 'userId')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workflows', sa.Column('userId', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'workflows', type_='foreignkey')
    op.create_foreign_key(op.f('workflows_userId_fkey'), 'workflows', 'users', ['userId'], ['id'])
    op.drop_column('workflows', 'user_id')
    # ### end Alembic commands ###
