"""Added Account name

Revision ID: 7629fcf19c92
Revises: da56caac3e14
Create Date: 2026-03-21 20:51:08.374297

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7629fcf19c92'
down_revision: Union[str, Sequence[str], None] = 'da56caac3e14'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('workflows_accountName_key'), 'workflows', type_='unique')
    op.drop_column('workflows', 'accountName')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workflows', sa.Column('accountName', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_unique_constraint(op.f('workflows_accountName_key'), 'workflows', ['accountName'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
