"""form model

Revision ID: af8cce44bb00
Revises: c217bbd2e84c
Create Date: 2026-03-23 06:00:08.482230

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af8cce44bb00'
down_revision: Union[str, Sequence[str], None] = 'c217bbd2e84c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('form_configs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('workflow_id', sa.String(), nullable=False),
    sa.Column('node_id', sa.String(), nullable=False),
    sa.Column('form_elements', sa.JSON(), nullable=False),
    sa.Column('form_title', sa.String(), nullable=True),
    sa.Column('form_description', sa.String(), nullable=True),
    sa.Column('accountName', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_form_configs_accountName'), 'form_configs', ['accountName'], unique=False)
    op.create_index(op.f('ix_form_configs_id'), 'form_configs', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_form_configs_id'), table_name='form_configs')
    op.drop_index(op.f('ix_form_configs_accountName'), table_name='form_configs')
    op.drop_table('form_configs')
    # ### end Alembic commands ###
