"""removed account anme

Revision ID: c2c43d9a34c1
Revises: 7629fcf19c92
Create Date: 2026-03-22 16:32:07.304815

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c2c43d9a34c1'
down_revision: Union[str, Sequence[str], None] = '7629fcf19c92'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('executions_accountName_key'), 'executions', type_='unique')
    op.drop_column('executions', 'accountName')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('executions', sa.Column('accountName', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_unique_constraint(op.f('executions_accountName_key'), 'executions', ['accountName'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
