"""corrected name

Revision ID: d225f78a9b04
Revises: 74da1f646420
Create Date: 2026-03-17 00:26:26.128651

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd225f78a9b04'
down_revision: Union[str, Sequence[str], None] = '74da1f646420'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('accountName', sa.String(), nullable=False))
    op.drop_constraint(op.f('users_accoutName_key'), 'users', type_='unique')
    op.create_unique_constraint(None, 'users', ['accountName'])
    op.drop_column('users', 'accoutName')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('accoutName', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'users', type_='unique')
    op.create_unique_constraint(op.f('users_accoutName_key'), 'users', ['accoutName'], postgresql_nulls_not_distinct=False)
    op.drop_column('users', 'accountName')
    # ### end Alembic commands ###
