"""Added Account name

Revision ID: da56caac3e14
Revises: f2f0b8023e75
Create Date: 2026-03-21 17:56:06.014503

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da56caac3e14'
down_revision: Union[str, Sequence[str], None] = 'f2f0b8023e75'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('executions', sa.Column('accountName', sa.String(), nullable=False))
    op.create_unique_constraint(None, 'executions', ['accountName'])
    op.add_column('workflows', sa.Column('accountName', sa.String(), nullable=False))
    op.create_unique_constraint(None, 'workflows', ['accountName'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'workflows', type_='unique')
    op.drop_column('workflows', 'accountName')
    op.drop_constraint(None, 'executions', type_='unique')
    op.drop_column('executions', 'accountName')
    # ### end Alembic commands ###
